# Site
name: 'Pramod Raghavendra Jayathirth'
description: 'Welcome to my Blog!!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'http://pramodjayathirth.dev/'
disqus:
  shortname: 'pramodjayathirth-dev'
email: 'rj.jayathirth@gmail.com'
comments: true

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    pramod:
      name:           pramod
      site:           https://pramodjayathirth.dev
      avatar:         assets/images/pramod.jpg
      bio:            "Software Engineer"
      email:          rj.jayathirth@gmail.com
      twitter:        https://www.instagram.com/ajna_transcendent
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: pramod
      avatar: /assets/images/welcome.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
theme: jekyll-theme-cayman
